wandb_mode: 'online' # 'online' for syncing, or 'disabled' for no tracking
project_name: Genotype-MLM
name: baseline
emb_dim: 256
ff_dim: 256
hidden_dim:  # for classifier, not used for MLM
num_heads: 4
num_layers: 6
dropout_prob: 0.1
mask_prob: 0.15
batch_size: 32
val_share: 0.15 # CV split
max_seq_len: 'auto'
epochs: 100
early_stopping_patience: 3
lr: 0.00005 
weight_decay: 0.01
print_progress_every: 1500
report_every: 750
save_vocab: False
save_model: False
random_state: 42
specials:   
  CLS: '[CLS]'
  PAD: '[PAD]'
  MASK: '[MASK]'
  UNK: '[UNK]'
data:
  threshold_year: 1970
  exclude_genotypes:
  # exclude_assembly_variants: 
  exclude_assembly_variants: ["=PARTIAL", "=MISTRANSLATION", "=HMM"]
  exclusion_chars: 
  # exclusion_chars: ['-']  
  gene_count_threshold: 35
  save_path: 
  # save_path: 'data/TESSy.pkl'
  # exclude_antibiotics: ['POL', 'DOR', 'MEM', 'IPM', 'ETP', 'TGC', 'COL', 'AMK']
  exclude_antibiotics: 
  ab_names_to_abbr:
    Amoxicillin/Clavulanic acid: 'AMC'
    Amikacin: 'AMK'
    Ampicillin: 'AMP'
    Amoxicillin: 'AMX'
    Ceftazidime: 'CAZ'
    Ciprofloxacin: 'CIP'
    Colistin: 'COL'
    Ceftriaxone: 'CRO'
    Cefotaxime: 'CTX'
    Doripenem: 'DOR'
    Ertapenem: 'ETP'
    Cefepime: 'FEP'
    Gentamicin: 'GEN'
    Imipenem: 'IPM'
    Levofloxacin: 'LVX'
    Meropenem: 'MEM'
    Moxifloxacin: 'MFX'
    Nalidixic acid: 'NAL'
    Netilmicin: 'NET'
    Norfloxacin: 'NOR'
    Ofloxacin: 'OFX'
    Piperacillin: 'PIP'
    Polymyxin B: 'POL'
    Tigecycline: 'TGC'
    Tobramycin: 'TOB'
    Piperacillin/Tazobactam: 'TZP'
    
  region_mapping:
    'Afghanistan': 'Asia'
    'Albania': 'Europe'
    'Algeria': 'Africa'
    'Angola': 'Africa'
    'Antarctica': 'Oceania'
    'Argentina': 'South America'
    'Armenia': 'Asia'
    'Australia': 'Oceania'
    'Austria': 'Europe'
    'Bahrain': 'Asia'
    'Bangladesh': 'Asia'
    'Belarus': 'Europe'
    'Belgium': 'Europe'
    'Benin': 'Africa'
    'Bolivia': 'South America'
    'Botswana': 'Africa'
    'Brazil': 'South America'
    'Brunei': 'Asia'
    'Bulgaria': 'Europe'
    'Burkina Faso': 'Africa'
    'Burundi': 'Africa'
    'Cambodia': 'Asia'
    'Cameroon': 'Africa'
    'Canada': 'North America'
    'Chile': 'South America'
    'China': 'Asia'
    'Colombia': 'South America'
    'Costa Rica': 'North America'
    "Cote d'Ivoire": 'Africa'
    'Croatia': 'Europe'
    'Cuba': 'North America'
    'Cyprus': 'Europe'
    'Czech Republic': 'Europe'
    'Democratic Republic of the Congo': 'Africa'
    'Denmark': 'Europe'
    'Djibouti': 'Africa'
    'Dominican Republic': 'North America'
    'Ecuador': 'South America'
    'Egypt': 'Africa'
    'Estonia': 'Europe'
    'Ethiopia': 'Africa'
    'Finland': 'Europe'
    'France': 'Europe'
    'France and Algeria': 'Europe'
    'Gabon': 'Africa'
    'Gambia': 'Africa'
    'Georgia': 'Asia'
    'Germany': 'Europe'
    'Ghana': 'Africa'
    'Greece': 'Europe'
    'Greenland': 'Europe'
    'Guadeloupe': 'North America'
    'Guam': 'Oceania'
    'Guatemala': 'North America'
    'Guinea': 'Africa'
    'Guinea-Bissau': 'Africa'
    'Guyana': 'South America'
    'Haiti': 'North America'
    'Honduras': 'North America'
    'Hong Kong': 'Asia'
    'Hungary': 'Europe'
    'Iceland': 'Europe'
    'India': 'Asia'
    'Indonesia': 'Asia'
    'Iran': 'Asia'
    'Iraq': 'Asia'
    'Ireland': 'Europe'
    'Israel': 'Asia'
    'Italy': 'Europe'
    'Japan': 'Asia'
    'Jordan': 'Asia'
    'Kazakhstan': 'Europe'
    'Kenya': 'Africa'
    'Korea': 'Asia'
    'Kosovo': 'Europe'
    'Kuwait': 'Asia'
    'Kyrgyzstan': 'Asia'
    'Laos': 'Asia'
    'Latvia': 'Europe'
    'Lebanon': 'Asia'
    'Lithuania': 'Europe'
    'Luxembourg': 'Europe'
    'Macedonia': 'Europe'
    'Madagascar': 'Africa'
    'Malawi': 'Africa'
    'Malaysia': 'Asia'
    'Mali': 'Africa'
    'Mauritius': 'Africa'
    'Mexico': 'North America'
    'Mongolia': 'Asia'
    'Morocco': 'Africa'
    'Mozambique': 'Africa'
    'Myanmar': 'Asia'
    'Namibia': 'Africa'
    'Nepal': 'Asia'
    'Netherlands': 'Europe'
    'New Caledonia': 'Oceania'
    'New Zealand': 'Oceania'
    'Nicaragua': 'North America'
    'Niger': 'Africa'
    'Nigeria': 'Africa'
    'North America': 'North America'
    'Norway': 'Europe'
    'Oceania': 'Oceania'
    'Pacific Ocean': 'Oceania'
    'Pakistan': 'Asia'
    'Palestine': 'Asia'
    'Panama': 'North America'
    'Papua New Guinea': 'Oceania'
    'Paraguay': 'South America'
    'Peru': 'South America'
    'Philippines': 'Asia'
    'Poland': 'Europe'
    'Portugal': 'Europe'
    'Puerto Rico': 'North America'
    'Qatar': 'Asia'
    'Republic of the Congo': 'Africa'
    'Reunion': 'Africa'
    'Romania': 'Europe'
    'Russia': 'Europe'
    'Rwanda': 'Africa'
    'Saudi Arabia': 'Asia'
    'Senegal': 'Africa'
    'Serbia': 'Europe'
    'Singapore': 'Asia'
    'Slovakia': 'Europe'
    'Slovenia': 'Europe'
    'Somalia': 'Africa'
    'South Africa': 'Africa'
    'South America': 'South America'
    'South Korea': 'Asia'
    'South Sudan': 'Africa'
    'Spain': 'Europe'
    'Sri Lanka': 'Asia'
    'Sudan': 'Africa'
    'Sweden': 'Europe'
    'Switzerland': 'Europe'
    'Syria': 'Asia'
    'Taiwan': 'Asia'
    'Tanzania': 'Africa'
    'Thailand': 'Asia'
    'Togo': 'Africa'
    'Tonga': 'Oceania'
    'Tunisia': 'Africa'
    'Turkey': 'Asia'
    'UAE': 'Asia'
    'UK': 'Europe'
    'Uganda': 'Africa'
    'Ukraine': 'Europe'
    'United Arab Emirates': 'Asia'
    'Uruguay': 'South America'
    'USA': 'North America'
    'Uzbekistan': 'Asia'
    'Venezuela': 'South America'
    'Viet Nam': 'Asia'
    'West Bank': 'Asia'
    'Zaire': 'Africa'
    'Zambia': 'Africa'