wandb_name: mask_prob=0.25
emb_dim: 64
hidden_dim: 128
num_heads: 4
num_encoder_layers: 4
dropout_prob: 0.1
mask_prob: 0.25
batch_size: 32
epochs: 3
early_stopping_patience: 3
# learning_rate: 0.00005 # for BS 16
learning_rate: 0.0001 # for BS 32
# learning_rate: 0.0005 # for BS 64
weight_decay: 0.001
print_progress_every: 1500
report_every: 500
save_vocab: True 