project_name: Genotype-MLM
name: baseline
emb_dim: 256
ff_dim: 256
num_heads: 4
num_layers: 6
dropout_prob: 0.1
mask_prob: 0.15
batch_size: 32
split: [0.8, 0.1, 0.1] # train, val, test
max_seq_len: 'auto'
do_testing: False
epochs: 100
early_stopping_patience: 3
lr: 0.00005 
weight_decay: 0.01
print_progress_every: 1000
report_every: 500
save_vocab: False   # True for fine-tuning or inference 
save_model: False   # True for fine-tuning or inference
random_state: 42
data:
  threshold_year: 1970
  exclude_genotypes:
  # exclude_assembly_variants: 
  exclude_assembly_variants: ["=PARTIAL", "=MISTRANSLATION", "=HMM"]
  # exclusion_chars: 
  exclusion_chars: ['-']  
specials:   
  CLS: '[CLS]'
  PAD: '[PAD]'
  MASK: '[MASK]'
  UNK: '[UNK]'