project_name: Phenotype-MLM
name: sep_pheno
emb_dim: 256
hidden_dim: 256
num_heads: 4
num_layers: 4
dropout_prob: 0.1
mask_prob: 0.25
batch_size: 32
split: [0.8, 0.1, 0.1] # train, val, test
separate_phenotypes: True
max_seq_len: 'auto'
do_testing: False
epochs: 20
early_stopping_patience: 5
lr: 0.00001 
weight_decay: 0.01
print_progress_every: 3000
report_every: 1000
save_vocab: False   # True for fine-tuning or inference 
save_model: False   # True for fine-tuning or inference
random_state: 42
data:
  prepare_data: True
  path: 'data/raw/AMR_TEST.csv'
  save_path: 'data/TESSy.pkl'
  exclude_antibiotics: ['POL', 'DOR', 'MEM', 'IPM', 'ETP', 'TGC']
  pathogens: ['ESCCOL']
  impute_age: False
  impute_gender: False
specials:   
  CLS: '[CLS]'
  PAD: '[PAD]'
  MASK: '[MASK]'
  UNK: '[UNK]'