wandb_mode: 'online' # 'online' for syncing, or 'disabled' for no tracking
project_name: Genotype-MLM
name: baseline
emb_dim: 256
ff_dim: 256
hidden_dim:  # for classifier, not used for MLM
num_heads: 4
num_layers: 6
dropout_prob: 0.1
mask_prob: 0.15
batch_size: 32
val_share: 0.15 # CV split
max_seq_len: 'auto'
epochs: 100
early_stopping_patience: 3
lr: 0.00005 
weight_decay: 0.01
print_progress_every: 1000
report_every: 500
save_vocab: False 
save_model: False
random_state: 42
data:
  threshold_year: 1970
  exclude_genotypes:
  # exclude_assembly_variants: 
  exclude_assembly_variants: ["=PARTIAL", "=MISTRANSLATION", "=HMM"]
  exclusion_chars: 
  # exclusion_chars: ['-']  
  gene_count_threshold: 
  save_path: 
  # save_path: 'data/TESSy.pkl'
specials:   
  CLS: '[CLS]'
  PAD: '[PAD]'
  MASK: '[MASK]'
  UNK: '[UNK]'