wandb_name: test_run
emb_dim: 256 
hidden_dim: 512
num_heads: 8
num_encoder_layers: 12
dropout_prob: 0.1
mask_prob: 0.15
batch_size: 32
epochs: 5
early_stopping_patience: 3
# learning_rate: 0.00005 # for BS 16
learning_rate: 0.0001 # for BS 32
# learning_rate: 0.0005 # for BS 64
weight_decay: 0.001
print_progress_every: 1500
report_every: 500
save_vocab: True 