name: ARFusion
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchtext
  - pytorch-cuda=12.1
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn